version: "3.8"
volumes:
  node_modules:
services:
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./data/:/app/data:ro
      - ./conf/nginx/${NGINX_CONF:-local-api}.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:4000"
  api:
    build:
      dockerfile: docker/Dockerfile.api
      cache_from:
        - us-central1-docker.pkg.dev/cllimate/cllimate/api:latest
    image: us-central1-docker.pkg.dev/cllimate/cllimate/api:${TAG:-latest}
    ports:
      - "4001:4001"
    restart: always
    volumes:
      - ./:/app
      - ${GCLOUD_CONFIG_PATH:-~/.config/gcloud}:/root/.config/gcloud
    command: uvicorn cllimate.api:app --port 4001 --host 0.0.0.0 --reload
    environment:
      - TWILIO_AUTH_TOKEN
      - VITE_STATIC_HOST=http://nginx:4000
  site:
    build:
      dockerfile: docker/Dockerfile.site
      cache_from:
        - us-central1-docker.pkg.dev/cllimate/cllimate/site:latest
    image: us-central1-docker.pkg.dev/cllimate/cllimate/site:${TAG:-latest}
    restart: always
    volumes:
      - ./site:/site
      - node_modules:/app/node_modules
      - ${GCLOUD_CONFIG_PATH:-~/.config/gcloud}:/root/.config/gcloud
    command: bash -c "npm install && npm run dev -- --host --port 4002"
    ports:
      - "4002:4002"
    depends_on:
      - nginx
    environment:
      - VITE_STATIC_HOST=http://nginx:4000
      - VITE_API_HOST=http://nginx:4000
