FROM python:3.10

WORKDIR /app
RUN pip install wheel
ADD requirements.txt ./
RUN pip install -r requirements.txt

COPY . ./
RUN pip install -e .
ENV PORT=${PORT:-8000}
CMD uvicorn cllimate.api:app --host 0.0.0.0 --port ${PORT}
